spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/menus
    username: redis
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/master.yaml
    drop-first: false

redis:
  server:
    url: redis://localhost:6379

server:
  port: 8181

ms.payment:
    url: https://payment-texnoera.onrender.com/v1/payments

ms.restoran:
    url: http://localhost:8080/api/v1/restorans


